class LanguageList {
  static final langs = [
    'auto-Automatic',
    'af-Afrikaans',
    'sq-Albanian',
    'am-Amharic',
    'ar-Arabic',
    'hy-Armenian',
    'az-Azerbaijani',
    'eu-Basque',
    'be-Belarusian',
    'bn-Bengali',
    'bs-Bosnian',
    'bg-Bulgarian',
    'ca-Catalan',
    'ceb-Cebuano',
    'ny-Chichewa',
    'zh-cn-Chinese Simplified',
    'zh-tw-Chinese Traditional',
    'co-Corsican',
    'hr-Croatian',
    'cs-Czech',
    'da-Danish',
    'nl-Dutch',
    'en-English',
    'eo-Esperanto',
    'et-Estonian',
    'tl-Filipino',
    'fi-Finnish',
    'fr-French',
    'fy-Frisian',
    'gl-Galician',
    'ka-Georgian',
    'de-German',
    'el-Greek',
    'gu-Gujarati',
    'ht-Haitian Creole',
    'ha-Hausa',
    'haw-Hawaiian',
    'iw-Hebrew',
    'hi-Hindi',
    'hmn-Hmong',
    'hu-Hungarian',
    'is-Icelandic',
    'ig-Igbo',
    'id-Indonesian',
    'ga-Irish',
    'it-Italian',
    'ja-Japanese',
    'jw-Javanese',
    'kn-Kannada',
    'kk-Kazakh',
    'km-Khmer',
    'ko-Korean',
    'ku-Kurdish (Kurmanji)',
    'ky-Kyrgyz',
    'lo-Lao',
    'la-Latin',
    'lv-Latvian',
    'lt-Lithuanian',
    'lb-Luxembourgish',
    'mk-Macedonian',
    'mg-Malagasy',
    'ms-Malay',
    'ml-Malayalam',
    'mt-Maltese',
    'mi-Maori',
    'mr-Marathi',
    'mn-Mongolian',
    'my-Myanmar (Burmese)',
    'ne-Nepali',
    'no-Norwegian',
    'ps-Pashto',
    'fa-Persian',
    'pl-Polish',
    'pt-Portuguese',
    'pa-Punjabi',
    'ro-Romanian',
    'ru-Russian',
    'sm-Samoan',
    'gd-Scots Gaelic',
    'sr-Serbian',
    'st-Sesotho',
    'sn-Shona',
    'sd-Sindhi',
    'si-Sinhala',
    'sk-Slovak',
    'sl-Slovenian',
    'so-Somali',
    'es-Spanish',
    'su-Sundanese',
    'sw-Swahili',
    'sv-Swedish',
    'tg-Tajik',
    'ta-Tamil',
    'te-Telugu',
    'th-Thai',
    'tr-Turkish',
    'uk-Ukrainian',
    'ur-Urdu',
    'uz-Uzbek',
    'ug-Uyghur',
    'vi-Vietnamese',
    'cy-Welsh',
    'xh-Xhosa',
    'yi-Yiddish',
    'yo-Yoruba',
    'zu-Zulu'
  ];
}

class MyClass {
  dynamic field1;
  dynamic field2;
  dynamic field3;
  dynamic field4;

  MyClass({
    this.field1,
    this.field2,
    this.field3,
    this.field4,
  });

  factory MyClass.fromJson(dynamic json) {
    return MyClass(
      field1: json['field1'],
      field2: json['field2'],
      field3: json['field3'],
      field4: json['field4'],
    );


  }
}